stages: # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build-job: # This job runs in the build stage, which runs first.
  variables:
    my_name: "hahahahaha"
  stage: build
  tags:
    - shell
    - local-gitlab-runner
  script:
    - pwd
    - ls -a
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - echo $DATABASE_URL
    - echo $DATABASE_URL > .env
  artifacts:
    paths:
      - venv
      - .env
    expire_in: 1 week

test-job:
  tags:
    - shell
    - local-gitlab-runner
  script:
    - pwd
    - ls -a
    - source venv/bin/activate
    - pytest
