services:
  iqm_mysql2:
    image: mysql:5.7
    container_name: iqm_mysql2
    #command: mysqld --default-authentication-plugin=mysql_native_password
    ports:
      - 6978:3307
    environment:
      - MYSQL_DATABASE=iqmdb
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=test
      - TZ='Asia/Taipei'
    volumes:
      - iqm_mysql_volume2:/var/lib/mysql
    restart: always
  # phpmyadmin2:
  #   image: phpmyadmin:latest
  #   container_name: iqm_phpmyadmin2
  #   ports:
  #     - 6976:80
  #   environment:
  #     - PMA_HOST=iqm_mysql2
  #   links:
  #     - iqm_mysql2
  #   depends_on:
  #     - iqm_mysql2
  #   restart: always

  volumes:
    iqm_mysql_volume2:
      external: true
